//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.PhongService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="phong", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHotelManager.Entity")]
    [System.SerializableAttribute()]
    public partial class phong : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_lpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QuanLyKhachSan.PhongService.loaiPhong LoaiPhongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrangthaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_lp {
            get {
                return this.Id_lpField;
            }
            set {
                if ((this.Id_lpField.Equals(value) != true)) {
                    this.Id_lpField = value;
                    this.RaisePropertyChanged("Id_lp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QuanLyKhachSan.PhongService.loaiPhong LoaiPhong {
            get {
                return this.LoaiPhongField;
            }
            set {
                if ((object.ReferenceEquals(this.LoaiPhongField, value) != true)) {
                    this.LoaiPhongField = value;
                    this.RaisePropertyChanged("LoaiPhong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Trangthai {
            get {
                return this.TrangthaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TrangthaiField, value) != true)) {
                    this.TrangthaiField = value;
                    this.RaisePropertyChanged("Trangthai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="loaiPhong", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHotelManager.Entity")]
    [System.SerializableAttribute()]
    public partial class loaiPhong : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoNguoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mota {
            get {
                return this.MotaField;
            }
            set {
                if ((object.ReferenceEquals(this.MotaField, value) != true)) {
                    this.MotaField = value;
                    this.RaisePropertyChanged("Mota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoNguoi {
            get {
                return this.SoNguoiField;
            }
            set {
                if ((this.SoNguoiField.Equals(value) != true)) {
                    this.SoNguoiField = value;
                    this.RaisePropertyChanged("SoNguoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="chitietdatphong", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHotelManager.Entity")]
    [System.SerializableAttribute()]
    public partial class chitietdatphong : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_pField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_pdpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QuanLyKhachSan.PhongService.phieudatphong PhieudatphongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QuanLyKhachSan.PhongService.phong PhongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_p {
            get {
                return this.Id_pField;
            }
            set {
                if ((this.Id_pField.Equals(value) != true)) {
                    this.Id_pField = value;
                    this.RaisePropertyChanged("Id_p");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_pdp {
            get {
                return this.Id_pdpField;
            }
            set {
                if ((this.Id_pdpField.Equals(value) != true)) {
                    this.Id_pdpField = value;
                    this.RaisePropertyChanged("Id_pdp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QuanLyKhachSan.PhongService.phieudatphong Phieudatphong {
            get {
                return this.PhieudatphongField;
            }
            set {
                if ((object.ReferenceEquals(this.PhieudatphongField, value) != true)) {
                    this.PhieudatphongField = value;
                    this.RaisePropertyChanged("Phieudatphong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QuanLyKhachSan.PhongService.phong Phong {
            get {
                return this.PhongField;
            }
            set {
                if ((object.ReferenceEquals(this.PhongField, value) != true)) {
                    this.PhongField = value;
                    this.RaisePropertyChanged("Phong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="phieudatphong", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHotelManager.Entity")]
    [System.SerializableAttribute()]
    public partial class phieudatphong : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_khField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QuanLyKhachSan.PhongService.khachhang KhachhangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgaydenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgaydiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SonguoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TiendatcocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TinhtrangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_kh {
            get {
                return this.Id_khField;
            }
            set {
                if ((this.Id_khField.Equals(value) != true)) {
                    this.Id_khField = value;
                    this.RaisePropertyChanged("Id_kh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QuanLyKhachSan.PhongService.khachhang Khachhang {
            get {
                return this.KhachhangField;
            }
            set {
                if ((object.ReferenceEquals(this.KhachhangField, value) != true)) {
                    this.KhachhangField = value;
                    this.RaisePropertyChanged("Khachhang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ngayden {
            get {
                return this.NgaydenField;
            }
            set {
                if ((this.NgaydenField.Equals(value) != true)) {
                    this.NgaydenField = value;
                    this.RaisePropertyChanged("Ngayden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ngaydi {
            get {
                return this.NgaydiField;
            }
            set {
                if ((this.NgaydiField.Equals(value) != true)) {
                    this.NgaydiField = value;
                    this.RaisePropertyChanged("Ngaydi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Songuoi {
            get {
                return this.SonguoiField;
            }
            set {
                if ((this.SonguoiField.Equals(value) != true)) {
                    this.SonguoiField = value;
                    this.RaisePropertyChanged("Songuoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Tiendatcoc {
            get {
                return this.TiendatcocField;
            }
            set {
                if ((this.TiendatcocField.Equals(value) != true)) {
                    this.TiendatcocField = value;
                    this.RaisePropertyChanged("Tiendatcoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tinhtrang {
            get {
                return this.TinhtrangField;
            }
            set {
                if ((object.ReferenceEquals(this.TinhtrangField, value) != true)) {
                    this.TinhtrangField = value;
                    this.RaisePropertyChanged("Tinhtrang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="khachhang", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHotelManager.Entity")]
    [System.SerializableAttribute()]
    public partial class khachhang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GioitinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SdtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cmt {
            get {
                return this.CmtField;
            }
            set {
                if ((object.ReferenceEquals(this.CmtField, value) != true)) {
                    this.CmtField = value;
                    this.RaisePropertyChanged("Cmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Gioitinh {
            get {
                return this.GioitinhField;
            }
            set {
                if ((this.GioitinhField.Equals(value) != true)) {
                    this.GioitinhField = value;
                    this.RaisePropertyChanged("Gioitinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hoten {
            get {
                return this.HotenField;
            }
            set {
                if ((object.ReferenceEquals(this.HotenField, value) != true)) {
                    this.HotenField = value;
                    this.RaisePropertyChanged("Hoten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sdt {
            get {
                return this.SdtField;
            }
            set {
                if ((object.ReferenceEquals(this.SdtField, value) != true)) {
                    this.SdtField = value;
                    this.RaisePropertyChanged("Sdt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="chitietdichvu", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHotelManager.Entity")]
    [System.SerializableAttribute()]
    public partial class chitietdichvu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QuanLyKhachSan.PhongService.dichvu DichvuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_dvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_pdpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QuanLyKhachSan.PhongService.phieudatphong PhieudatphongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoluongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QuanLyKhachSan.PhongService.dichvu Dichvu {
            get {
                return this.DichvuField;
            }
            set {
                if ((object.ReferenceEquals(this.DichvuField, value) != true)) {
                    this.DichvuField = value;
                    this.RaisePropertyChanged("Dichvu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_dv {
            get {
                return this.Id_dvField;
            }
            set {
                if ((this.Id_dvField.Equals(value) != true)) {
                    this.Id_dvField = value;
                    this.RaisePropertyChanged("Id_dv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_pdp {
            get {
                return this.Id_pdpField;
            }
            set {
                if ((this.Id_pdpField.Equals(value) != true)) {
                    this.Id_pdpField = value;
                    this.RaisePropertyChanged("Id_pdp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QuanLyKhachSan.PhongService.phieudatphong Phieudatphong {
            get {
                return this.PhieudatphongField;
            }
            set {
                if ((object.ReferenceEquals(this.PhieudatphongField, value) != true)) {
                    this.PhieudatphongField = value;
                    this.RaisePropertyChanged("Phieudatphong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Soluong {
            get {
                return this.SoluongField;
            }
            set {
                if ((this.SoluongField.Equals(value) != true)) {
                    this.SoluongField = value;
                    this.RaisePropertyChanged("Soluong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dichvu", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHotelManager.Entity")]
    [System.SerializableAttribute()]
    public partial class dichvu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DonvitinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_ldvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QuanLyKhachSan.PhongService.loaidichvu LoaidichvuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Donvitinh {
            get {
                return this.DonvitinhField;
            }
            set {
                if ((object.ReferenceEquals(this.DonvitinhField, value) != true)) {
                    this.DonvitinhField = value;
                    this.RaisePropertyChanged("Donvitinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_ldv {
            get {
                return this.Id_ldvField;
            }
            set {
                if ((this.Id_ldvField.Equals(value) != true)) {
                    this.Id_ldvField = value;
                    this.RaisePropertyChanged("Id_ldv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QuanLyKhachSan.PhongService.loaidichvu Loaidichvu {
            get {
                return this.LoaidichvuField;
            }
            set {
                if ((object.ReferenceEquals(this.LoaidichvuField, value) != true)) {
                    this.LoaidichvuField = value;
                    this.RaisePropertyChanged("Loaidichvu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="loaidichvu", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceHotelManager.Entity")]
    [System.SerializableAttribute()]
    public partial class loaidichvu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HesogiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hesogia {
            get {
                return this.HesogiaField;
            }
            set {
                if ((object.ReferenceEquals(this.HesogiaField, value) != true)) {
                    this.HesogiaField = value;
                    this.RaisePropertyChanged("Hesogia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Loai {
            get {
                return this.LoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.LoaiField, value) != true)) {
                    this.LoaiField = value;
                    this.RaisePropertyChanged("Loai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhongService.IphongApi")]
    public interface IphongApi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/getListPhong", ReplyAction="http://tempuri.org/IphongApi/getListPhongResponse")]
        QuanLyKhachSan.PhongService.phong[] getListPhong(int id_lp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/getListPhong", ReplyAction="http://tempuri.org/IphongApi/getListPhongResponse")]
        System.Threading.Tasks.Task<QuanLyKhachSan.PhongService.phong[]> getListPhongAsync(int id_lp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/getPhongById", ReplyAction="http://tempuri.org/IphongApi/getPhongByIdResponse")]
        QuanLyKhachSan.PhongService.chitietdatphong getPhongById(int idPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/getPhongById", ReplyAction="http://tempuri.org/IphongApi/getPhongByIdResponse")]
        System.Threading.Tasks.Task<QuanLyKhachSan.PhongService.chitietdatphong> getPhongByIdAsync(int idPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/getPhieuDatPhongById", ReplyAction="http://tempuri.org/IphongApi/getPhieuDatPhongByIdResponse")]
        QuanLyKhachSan.PhongService.chitietdatphong getPhieuDatPhongById(int idPdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/getPhieuDatPhongById", ReplyAction="http://tempuri.org/IphongApi/getPhieuDatPhongByIdResponse")]
        System.Threading.Tasks.Task<QuanLyKhachSan.PhongService.chitietdatphong> getPhieuDatPhongByIdAsync(int idPdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/ktraPhong", ReplyAction="http://tempuri.org/IphongApi/ktraPhongResponse")]
        int ktraPhong(int idPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/ktraPhong", ReplyAction="http://tempuri.org/IphongApi/ktraPhongResponse")]
        System.Threading.Tasks.Task<int> ktraPhongAsync(int idPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/getDichVuPdp", ReplyAction="http://tempuri.org/IphongApi/getDichVuPdpResponse")]
        QuanLyKhachSan.PhongService.chitietdichvu[] getDichVuPdp(int idPdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/getDichVuPdp", ReplyAction="http://tempuri.org/IphongApi/getDichVuPdpResponse")]
        System.Threading.Tasks.Task<QuanLyKhachSan.PhongService.chitietdichvu[]> getDichVuPdpAsync(int idPdp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/traphong", ReplyAction="http://tempuri.org/IphongApi/traphongResponse")]
        bool traphong(int idPdp, double tongtien, string username, int idp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/traphong", ReplyAction="http://tempuri.org/IphongApi/traphongResponse")]
        System.Threading.Tasks.Task<bool> traphongAsync(int idPdp, double tongtien, string username, int idp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/getListDichVu", ReplyAction="http://tempuri.org/IphongApi/getListDichVuResponse")]
        QuanLyKhachSan.PhongService.dichvu[] getListDichVu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/getListDichVu", ReplyAction="http://tempuri.org/IphongApi/getListDichVuResponse")]
        System.Threading.Tasks.Task<QuanLyKhachSan.PhongService.dichvu[]> getListDichVuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/themdv", ReplyAction="http://tempuri.org/IphongApi/themdvResponse")]
        bool themdv(int iddv, int idpdp, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/themdv", ReplyAction="http://tempuri.org/IphongApi/themdvResponse")]
        System.Threading.Tasks.Task<bool> themdvAsync(int iddv, int idpdp, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/getLoaidichvu", ReplyAction="http://tempuri.org/IphongApi/getLoaidichvuResponse")]
        QuanLyKhachSan.PhongService.loaidichvu[] getLoaidichvu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/getLoaidichvu", ReplyAction="http://tempuri.org/IphongApi/getLoaidichvuResponse")]
        System.Threading.Tasks.Task<QuanLyKhachSan.PhongService.loaidichvu[]> getLoaidichvuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/updatedv", ReplyAction="http://tempuri.org/IphongApi/updatedvResponse")]
        bool updatedv(QuanLyKhachSan.PhongService.dichvu dv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/updatedv", ReplyAction="http://tempuri.org/IphongApi/updatedvResponse")]
        System.Threading.Tasks.Task<bool> updatedvAsync(QuanLyKhachSan.PhongService.dichvu dv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/xoadv", ReplyAction="http://tempuri.org/IphongApi/xoadvResponse")]
        bool xoadv(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IphongApi/xoadv", ReplyAction="http://tempuri.org/IphongApi/xoadvResponse")]
        System.Threading.Tasks.Task<bool> xoadvAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IphongApiChannel : QuanLyKhachSan.PhongService.IphongApi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IphongApiClient : System.ServiceModel.ClientBase<QuanLyKhachSan.PhongService.IphongApi>, QuanLyKhachSan.PhongService.IphongApi {
        
        public IphongApiClient() {
        }
        
        public IphongApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IphongApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IphongApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IphongApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QuanLyKhachSan.PhongService.phong[] getListPhong(int id_lp) {
            return base.Channel.getListPhong(id_lp);
        }
        
        public System.Threading.Tasks.Task<QuanLyKhachSan.PhongService.phong[]> getListPhongAsync(int id_lp) {
            return base.Channel.getListPhongAsync(id_lp);
        }
        
        public QuanLyKhachSan.PhongService.chitietdatphong getPhongById(int idPhong) {
            return base.Channel.getPhongById(idPhong);
        }
        
        public System.Threading.Tasks.Task<QuanLyKhachSan.PhongService.chitietdatphong> getPhongByIdAsync(int idPhong) {
            return base.Channel.getPhongByIdAsync(idPhong);
        }
        
        public QuanLyKhachSan.PhongService.chitietdatphong getPhieuDatPhongById(int idPdp) {
            return base.Channel.getPhieuDatPhongById(idPdp);
        }
        
        public System.Threading.Tasks.Task<QuanLyKhachSan.PhongService.chitietdatphong> getPhieuDatPhongByIdAsync(int idPdp) {
            return base.Channel.getPhieuDatPhongByIdAsync(idPdp);
        }
        
        public int ktraPhong(int idPhong) {
            return base.Channel.ktraPhong(idPhong);
        }
        
        public System.Threading.Tasks.Task<int> ktraPhongAsync(int idPhong) {
            return base.Channel.ktraPhongAsync(idPhong);
        }
        
        public QuanLyKhachSan.PhongService.chitietdichvu[] getDichVuPdp(int idPdp) {
            return base.Channel.getDichVuPdp(idPdp);
        }
        
        public System.Threading.Tasks.Task<QuanLyKhachSan.PhongService.chitietdichvu[]> getDichVuPdpAsync(int idPdp) {
            return base.Channel.getDichVuPdpAsync(idPdp);
        }
        
        public bool traphong(int idPdp, double tongtien, string username, int idp) {
            return base.Channel.traphong(idPdp, tongtien, username, idp);
        }
        
        public System.Threading.Tasks.Task<bool> traphongAsync(int idPdp, double tongtien, string username, int idp) {
            return base.Channel.traphongAsync(idPdp, tongtien, username, idp);
        }
        
        public QuanLyKhachSan.PhongService.dichvu[] getListDichVu() {
            return base.Channel.getListDichVu();
        }
        
        public System.Threading.Tasks.Task<QuanLyKhachSan.PhongService.dichvu[]> getListDichVuAsync() {
            return base.Channel.getListDichVuAsync();
        }
        
        public bool themdv(int iddv, int idpdp, int soluong) {
            return base.Channel.themdv(iddv, idpdp, soluong);
        }
        
        public System.Threading.Tasks.Task<bool> themdvAsync(int iddv, int idpdp, int soluong) {
            return base.Channel.themdvAsync(iddv, idpdp, soluong);
        }
        
        public QuanLyKhachSan.PhongService.loaidichvu[] getLoaidichvu() {
            return base.Channel.getLoaidichvu();
        }
        
        public System.Threading.Tasks.Task<QuanLyKhachSan.PhongService.loaidichvu[]> getLoaidichvuAsync() {
            return base.Channel.getLoaidichvuAsync();
        }
        
        public bool updatedv(QuanLyKhachSan.PhongService.dichvu dv) {
            return base.Channel.updatedv(dv);
        }
        
        public System.Threading.Tasks.Task<bool> updatedvAsync(QuanLyKhachSan.PhongService.dichvu dv) {
            return base.Channel.updatedvAsync(dv);
        }
        
        public bool xoadv(int id) {
            return base.Channel.xoadv(id);
        }
        
        public System.Threading.Tasks.Task<bool> xoadvAsync(int id) {
            return base.Channel.xoadvAsync(id);
        }
    }
}
